{% set version = "0.4.2" %}

package:
  name: testpath
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/testpath/testpath-{{ version }}.tar.gz
  sha256: b694b3d9288dbd81685c5d2e7140b81365d46c29f5db4bc659de5aa6b98780f8

build:
  number: 0
  skip: True  # [py2k]
  script: {{PYTHON}} -m flit install --deps=none

requirements:
  host:
    - python
    - flit
  run:
    - python

test:
  imports:
    - testpath

about:
  home: https://testpath.readthedocs.io
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Testpath is a collection of utilities for Python code working with files and commands.
  description: |
    Testpath contains functions to check things on the filesystem,
    and tools for mocking system commands and recording calls to those.
  doc_url: https://testpath.readthedocs.io
  dev_url: https://github.com/jupyter/testpath

extra:
  recipe-maintainers:
    - minrk
    - takluyver
    - ocefpaf
