travis:
  secure:
    BINSTAR_TOKEN: Jb9NrKls2Jv6n+KD0MvqotvhasqAK5eKcvjNpwsi0xBzQS6NxZtVSeeqIWJTaFl8xWvTlj7XlzzHmCdaZ8kzOo2pYckcl2gxjQ2iLSnV6lcJ+RTDDOhEHK36cgSzTaBke5x4sjwTb83lRYzarh/mS12YNgQQNlZrWNHMNIdKjLgPt6iY9hhSH0c76RgKVqZQtfxHSNgHKdOXyCaG8Qr8yjNVmix7G8h9aV0Ut8Ek0biZX1JoXye9vBu1mVH15tSluShKtm1GQ6APvMa2IYEWNmEGZwvTQQFLX0LKk2OC93kLMJ0Iv2J3WiTI6jAaCikzxx8xx1Peg52Rc9lsygeoVnzL2hUIt8Zlv6Tv0E8oC8I7cR+AYZ4LZg1yg2G1k0hDw9zLIE3c61LyzDfTg7y8+hvchyvtcUwmGwgGusYs6HjnokgK7zVR0t5P63yAYbEEB0YNLo3ZXON4IHhU8fC0BW5UCukBY1U84tequTKaT5D+Eg+d28AtcgQ8zNFOZPZCWhkoEVmAPp2iyjIAmLqeRROJIg2VGZgOvcAe1qx57bAA1g26LuFzGdyd0gqxYaoRMmxRvcrbL/fjI5qUtaRTqAD20bktYW3nr/Rbut9zot91YXmZKab5+EythI3XJMh1EB7ACAQqFrVABat6mdwTRc1IhHKkg4M4I8Gr2NbWNvc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
