travis:
  secure:
    BINSTAR_TOKEN: F17O7HjIVqWq37mzTXapMM6NdFgIPhJATdwcbAkVIyBquuCB+x6pfilN9b63bKDNEFS2Qn5NP8Tdhvy24EU50DPGGPBTg3nrPVzDjHMAUsYLqA73g8Z2a4wsJLrzhY6Cixstrna1g7WoG3J4o+nMOY/gSoh5egBthtcUvhviDzemIm1O+lMWIXrN9Ul4Tm4PnDvfO9iCDre6a0atLidRcwdRvUuN1B157TMz3WobKcCwoak2s8xVhWfhX5O1DZGWI4NSqCpLRsqHnBskg9IHySqNI67NpcNhYSHHC1ccZ4yL7Q4PHHLNmZfLYdB5UPf+rayfflbDtyYQr2X9MYSohS4cwnW3RAjCdx7I+VbqCJ9bXEwDwDPjK9VE/GaL55t4I9glC6muHxeIstO62RIMmW5UAKiA51+zlPG2NiyA1aJWBKcP1b6idZ/RX2o4ml7ZArFHYTYpLdbK07HyfUTN1tLSlZ16xapKsXFSZgbNuqbV8aIi22+dyJOHO/VmWQ4RbLIxQBBWaD1Uyco61+Em9Ipq+k1ioIE6cBaCO3L5NkTWZMJYW6Bdkpkf2FDwT24V0Z9LZiUHNUCc8CEc8Lin29h2RMHRuuCbaBtxFbjKcFt7xkEPFrbttO7ruGIn9D8zKLFY9ZRS1naoPOGOvEk2wUT7Z+Ir/L+tmWyq5xf901g=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
